### ISSUE TITLE
Suggestion:  adc->ReferenceVoltage 

### ISSUE THREAD

**Issue by holgerlembke** [pedvide/ADC#6]
I do the following:

const float ReferenceVoltage = 1.2;
adc->setReference(ADC_REF_ALT);
...
result=adc->analogRead(PinMesswert) * ReferenceVoltage / adc->getMaxValue(ADC_0);

As far as I see I have to declase the referencevoltage. on the other hand the hardware definition prescribs this value if I use ADC_REF_ALT on that platform.

So why not do move that knowledge into the object and make it automatic? Having

adc->setReference(ADC_REF_ALT);
...
result=adc->analogRead(PinMesswert) * adc->ReferenceVoltage / adc->getMaxValue(ADC_0);

would look and feel much nicer to me.

**Comment by pedvide** [comment]
Hello and danke for the suggestion,

There are two main reasons not to do that.
The first is that the default reference is 3.3 V only if you power the Teensy with enough voltage on the VIN pin or the 3.3 V pin, but you can use Teensy with lower voltages (as low as 1.7-1.8 V in theory). The ADC library has no way of knowing what that voltage is!
A similar problem happens with the 1.2 V reference, it's indeed "fixed", but you can trim it a little bit from 1.16 V to 1.24 V, so if you need a very precise conversion you should measure the actual value.

The second reason is the use of floating point numbers in boards with no floating point hardware. It increases the code size a few kB. This is a problem for Teensy LC for example (6 kB increase!).

That's why it should be the user the one to convert the ADC counts to a final voltage.

PD: Note that since the Teensy LC is supported the setReference(type) function has as options: ADC_REF_3V3, ADC_REF_1V2 (not for Teensy LC) or ADC_REF_EXT.
